In [57]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
import matplotlib as plt
import numpy as np
import starter
import importlib
importlib.reload(starter)

<module 'starter' from 'c:\\Users\\erica\\OneDrive - ETH Zurich\\Exchange\\Machine Learning\\CS349---Group8\\HW2\\starter.py'>

## Part I

In [2]:
# dimensionality reduction
def reduce(train, valid, test, method):
    if method == 'pca':
        return starter.pca(train, valid, test)
    elif method == 'bin':
        return starter.binarize(train, valid, test)
    elif method == 'none':
        return starter.make_float(train, valid, test)
    
# test model
def evaluate_knn(train, query, distance_metric):

    labels=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    query_labels = [i[0] for i in query]
    query_data = [i[1] for i in query]
    result_labels = starter.knn(train, query_data, distance_metric)

    # performance metrics
    query_accuracy = accuracy_score(query_labels, result_labels)
    query_precision = precision_score(query_labels, result_labels, average='macro')
    query_recall = recall_score(query_labels, result_labels, average='macro')
    query_f1 = f1_score(query_labels, result_labels, average='macro')
    confusion = confusion_matrix(query_labels, result_labels, labels=labels)

    return query_accuracy, query_precision, query_recall, query_f1, confusion

In [3]:
mnist_train = starter.read_data('mnist_train.csv')
mnist_valid = starter.read_data('mnist_valid.csv')
mnist_test = starter.read_data('mnist_test.csv')

In [58]:
# reduce dimensionality
train, valid, test = reduce(mnist_train, mnist_valid, mnist_test, 'pca')

### KNN

In [19]:
# test on validation set
valid_accuracy, valid_precision, valid_recall, valid_f1, confusion = evaluate_knn(train, valid, 'euclidean')
print('Validation Set Performance')
print('Accuracy:', valid_accuracy)
print('Precision:', valid_precision)
print('Recall:', valid_recall)
print('F1:', valid_f1)

Validation Set Performance
Accuracy: 0.83
Precision: 0.835665299612668
Recall: 0.8356299799234581
F1: 0.8282949673148796


In [20]:
# test set performance
test_accuracy, test_precision, test_recall, test_f1, confusion = evaluate_knn(train, test, 'euclidean')
print('Test Set Performance')
print('Accuracy:', test_accuracy)
print('Precision:', test_precision)
print('Recall:', test_recall)
print('F1:', test_f1)

print(confusion)

Test Set Performance
Accuracy: 0.875
Precision: 0.878171255344243
Recall: 0.8732072430493483
F1: 0.8735102153633392
[[17  0  1  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  0  0]
 [ 0  2 14  0  0  0  1  1  1  0]
 [ 0  0  2 15  0  0  0  0  1  0]
 [ 0  0  0  0 23  0  0  1  0  1]
 [ 0  0  0  1  0 11  0  0  1  0]
 [ 0  0  0  0  0  0 13  0  0  0]
 [ 0  1  0  0  1  0  0 22  0  0]
 [ 2  0  0  1  0  1  0  0 16  1]
 [ 1  2  0  0  1  0  0  1  0 17]]


### K-Means

In [ ]:
# train k-means
# train association function
# test on validation set
# tune hyperparameters
# test on test set


labels = [i[0] for i in valid]
data = [i[1] for i in valid]

result_labels = starter.kmeans(train, data, 'euclidean')


In [60]:
unique_result_labels = set(result_labels)
counts = {result_label: [0 for integer in range(10)] for result_label in unique_result_labels}
for result_label, label in zip(result_labels, labels):
    counts[result_label][int(label)] += 1
mapping = {result_label: np.argmax(count) for result_label, count in counts.items()}

new_labels = [str(mapping[result_label]) for result_label in result_labels]

# performance metrics
query_accuracy = accuracy_score(labels, new_labels)
query_precision = precision_score(labels, new_labels, average='macro')
query_recall = recall_score(labels, new_labels, average='macro')
query_f1 = f1_score(labels, new_labels, average='macro')
confusion = confusion_matrix(labels, new_labels, labels=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
print('Validation Set Performance')
print('Accuracy:', query_accuracy)
print('Precision:', query_precision)
print('Recall:', query_recall)
print('F1:', query_f1)
print(confusion)


Validation Set Performance
Accuracy: 0.665
Precision: 0.6328937748766493
Recall: 0.6519018602170776
F1: 0.6137930431259023
[[13  0  1  1  0  0  1  0  0  0]
 [ 0 17  1  0  0  0  0  0  0  0]
 [ 1  0 14  2  0  0  1  1  3  0]
 [ 0  0  0 19  1  0  0  1  0  0]
 [ 1  1  1  0 17  0  0  1  1  0]
 [ 0  0  0 11  6  5  0  0  0  0]
 [ 2  3  0  0  0  0 17  0  1  0]
 [ 1  1  0  1  0  0  0 16  1  0]
 [ 0  1  0  4  1  1  0  0 15  0]
 [ 0  0  2  0  6  0  0  6  0  0]]


C:\Users\erica\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
