In [62]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
import matplotlib as plt
import numpy as np
import starter
import importlib
importlib.reload(starter)

<module 'starter' from 'c:\\Users\\erica\\OneDrive - ETH Zurich\\Exchange\\Machine Learning\\CS349---Group8\\HW2\\starter.py'>

## Part I

In [2]:
# dimensionality reduction
def reduce(train, valid, test, method):
    if method == 'pca':
        return starter.pca(train, valid, test)
    elif method == 'bin':
        return starter.binarize(train, valid, test)
    elif method == 'none':
        return starter.make_float(train, valid, test)
    
# test model
def evaluate_knn(train, query, distance_metric):

    labels=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    query_labels = [i[0] for i in query]
    query_data = [i[1] for i in query]
    result_labels = starter.knn(train, query_data, distance_metric)

    # performance metrics
    query_accuracy = accuracy_score(query_labels, result_labels)
    query_precision = precision_score(query_labels, result_labels, average='macro')
    query_recall = recall_score(query_labels, result_labels, average='macro')
    query_f1 = f1_score(query_labels, result_labels, average='macro')
    confusion = confusion_matrix(query_labels, result_labels, labels=labels)

    return query_accuracy, query_precision, query_recall, query_f1, confusion

In [3]:
mnist_train = starter.read_data('mnist_train.csv')
mnist_valid = starter.read_data('mnist_valid.csv')
mnist_test = starter.read_data('mnist_test.csv')

In [47]:
# reduce dimensionality
train, valid, test = reduce(mnist_train, mnist_valid, mnist_test, 'pca')

### KNN

In [55]:
# test on validation set
valid_accuracy, valid_precision, valid_recall, valid_f1, confusion = evaluate_knn(train, valid, 'euclidean')
print('Validation Set Performance')
print('Accuracy:', valid_accuracy)
print('Precision:', valid_precision)
print('Recall:', valid_recall)
print('F1:', valid_f1)

Validation Set Performance
Accuracy: 0.85
Precision: 0.8586694007746638
Recall: 0.8525780318715102
F1: 0.8500070140431186


In [56]:
# test set performance
test_accuracy, test_precision, test_recall, test_f1, confusion = evaluate_knn(train, test, 'euclidean')
print('Test Set Performance')
print('Accuracy:', test_accuracy)
print('Precision:', test_precision)
print('Recall:', test_recall)
print('F1:', test_f1)

print(confusion)

Test Set Performance
Accuracy: 0.895
Precision: 0.89490409233869
Recall: 0.885273518878782
F1: 0.8849462086495985
[[18  0  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  0  0]
 [ 0  1 16  0  0  0  0  1  1  0]
 [ 0  0  0 17  0  0  0  0  1  0]
 [ 0  0  0  0 24  0  0  0  0  1]
 [ 0  0  0  3  0  8  1  0  1  0]
 [ 0  0  0  0  0  0 13  0  0  0]
 [ 0  1  0  0  0  0  0 23  0  0]
 [ 1  1  1  1  0  1  0  0 15  1]
 [ 0  2  0  0  1  0  1  0  0 18]]


### K-Means

In [63]:
# labels = [i[0] for i in valid]
# data = [i[1] for i in valid]
labels = [i[0] for i in train]
data = [i[1] for i in train]
result_labels = starter.kmeans(train, data, 'euclidean')


In [64]:
unique_result_labels = set(result_labels)
counts = {result_label: [0 for integer in range(10)] for result_label in unique_result_labels}
for result_label, label in zip(result_labels, labels):
    counts[result_label][int(label)] += 1
mapping = {result_label: np.argmax(count) for result_label, count in counts.items()}
print(counts)
print(mapping)

{'e': [76, 0, 63, 0, 5, 8, 89, 0, 6, 0], 'd': [0, 0, 6, 12, 16, 3, 0, 125, 8, 53], 'h': [15, 2, 7, 5, 20, 97, 8, 18, 72, 5], 'j': [0, 0, 0, 2, 115, 9, 2, 36, 8, 113], 'a': [0, 0, 1, 1, 41, 1, 3, 7, 7, 14], 'c': [4, 1, 12, 7, 1, 6, 0, 1, 4, 0], 'i': [2, 230, 35, 31, 13, 6, 36, 18, 29, 4], 'f': [77, 0, 2, 0, 4, 4, 24, 0, 0, 0], 'g': [0, 0, 15, 2, 2, 0, 15, 0, 0, 0], 'b': [1, 1, 78, 147, 0, 45, 1, 0, 58, 5]}
{'e': 6, 'd': 7, 'h': 5, 'j': 4, 'a': 4, 'c': 2, 'i': 1, 'f': 0, 'g': 2, 'b': 3}
